# Generated by Django 5.2.4 on 2026-03-05 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stack_summary',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('db', 'Base de datos'), ('devops', 'DevOps'), ('other', 'Otros')], db_index=True, default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='technology',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='technology',
            name='slug',
            field=models.SlugField(blank=True, max_length=90),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_featured'], name='idx_project_status_feat'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['order', 'created_at'], name='idx_project_order_created'),
        ),
        migrations.AddIndex(
            model_name='technology',
            index=models.Index(fields=['category', 'order'], name='idx_tech_category_order'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('slug',), name='uq_project_slug'),
        ),
        migrations.AddConstraint(
            model_name='technology',
            constraint=models.UniqueConstraint(fields=('slug',), name='uq_technology_slug'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['project', 'order'], name='idx_projectimage_proj_order'),
        ),
    ]
