# Generated by Django 5.2.4 on 2026-03-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField()),
                ('deliverables', models.TextField(blank=True)),
                ('price_hint', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='idx_service_active_order')],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='uq_service_slug')],
            },
        ),
    ]
