# Generated by Django 5.2.4 on 2026-03-03 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Ingresa un teléfono válido.', regex='^[0-9+\\-() ]{7,30}$')])),
                ('message', models.TextField(max_length=2000)),
                ('source', models.CharField(blank=True, default='web', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='contact_lea_created_0c1f9c_idx'), models.Index(fields=['is_read'], name='contact_lea_is_read_a62fc9_idx'), models.Index(fields=['source'], name='contact_lea_source_9194a7_idx')],
            },
        ),
    ]
