# Generated by Django 5.2.4 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="subject",
            field=models.CharField(default="", max_length=200),
        ),
    ]
